name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          version: '317.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/Dockerfile.dev
          push: true
          tags: bujaretemi1998/react-test:latest
      - name: Check out setup-gcloud action
        uses: actions/checkout@v2
        with:
          repository: GoogleCloudPlatform/github-actions
          ref: v1.5.2
          path: gcloud
      - name: Deploy to Kubernetes  
        uses: ./gcloud/setup-gcloud
        with:
          project_id: multi-k8s-383816
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Set Kubectl context
        run: gcloud container clusters get-credentials multi-cluster
      - name: Deploy to Kubernetes
        run: ./deploy.sh
