on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
      - name: Decrypt JSON key file
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > service-account.json.enc
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }} -in service-account.json.enc -out service-account.json -d
      - name: Authenticate with gcloud
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project multi-k8s-384009
          gcloud config set compute/zone us-central1-c
          gcloud container clusters get-credentials multi-cluster
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bujaretemi1998/react-test:${{ github.sha }}
      - name: Run tests
        run: |
          docker run -e CI=true bujaretemi1998/react-test npm test
      - name: Deploy to Kubernetes
        run: |
          bash ./deploy.sh
