on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
      - name: Install gke-gcloud-auth-plugin
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
          sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      - name: Decrypt JSON key file
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }} -in service-account.json.enc -out service-account.json -d
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      - name: Authenticate with gcloud
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project multi-k8s-384009
          gcloud config set compute/zone us-central1-c
          gcloud container clusters get-credentials multi-cluster
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to Kubernetes
        run: |
          bash ./deploy.sh